# google search: ffprobe csv output get header row python
import csv


def get_ffprobe_csv_header(csv_file_path):
    """
    Reads the first row of an ffprobe CSV output file, assuming it's the header.

    Args:
        csv_file_path (str): The path to the ffprobe CSV output file.

    Returns:
        list: A list of strings representing the header row, or None if the file
              is empty or an error occurs.
    """
    try:
        with open(csv_file_path, 'r', newline='') as f:
            reader = csv.reader(f)
            header = next(reader)  # Read the first line (header)
            return header
    except FileNotFoundError:
        print(f"Error: File not found at {csv_file_path}")
        return None
    except StopIteration:
        print(f"Error: The CSV file at {csv_file_path} is empty.")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None


# Example usage:
if __name__ == "__main__":
    # Assuming 'ffprobe_output.csv' is the file generated by ffprobe
    # e.g., ffprobe -v error -select_streams v:0 -show_entries stream=codec_name,width,height -of csv=p=0:s=, input.mp4 > ffprobe_output.csv
    csv_file = 'ffprobe_output.csv'
    header_row = get_ffprobe_csv_header(csv_file)

    if header_row:
        print("CSV Header Row:")
        print(header_row)
